const ORDER_STATUSES = {
    PENDING: 'PENDING',
    CONFIRM: 'CONFIRM',
    RECEIVED: 'RECEIVED',
    INDELIVERY: 'INDELIVERY',
    COMPLETE: 'COMPLETE',
    CANCELLED: 'CANCELLED'
}

export default ORDER_STATUSES
